version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: dockerfile.dev
    image: ad-video-gen-dev
    container_name: ad-video-gen-dev
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
