version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    image: ad-video-gen
    container_name: ad-video-gen
    ports:
      - 8000:8000
    env_file:
      - .env
    restart: unless-stopped
